FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.fsproj ./
RUN dotnet restore

# copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build runtime image
FROM microsoft/dotnet:runtime

LABEL Name=fsharpdocker Version=0.0.1
EXPOSE 5000
WORKDIR /app
COPY --from=build-env /app/out ./
ENTRYPOINT ["dotnet", "GiraffeSample.dll"]